													--/Healthcare business domain


CREATE DATABASE Healthcare_Systems

USE Healthcare_Systems

---/0.1 TABLE PAYER
CREATE TABLE  PAYER
				(Id VARCHAR(MAX),	
				NAME VARCHAR(MAX),
				ADDRESS VARCHAR(MAX),
				CITY VARCHAR(MAX),
				STATE_HEADQUARTERED VARCHAR(MAX),	
				ZIP VARCHAR(MAX),	
				PHONE VARCHAR(MAX))

SELECT *FROM PAYER
----/LOADING DATA USING BULK INSERT ...
BULK INSERT PAYER
FROM 
	'C:\Users\VENU CHAVAN\OneDrive\Desktop\project 2 lern bay\payers.csv'
WITH(fieldterminator=',',rowterminator='\n',firstrow=2);

---/0.2 TABLE ENCOUNTERS

CREATE TABLE ENCOUNTERS
					(Id VARCHAR(MAX),
					START VARCHAR(MAX),
					STOP VARCHAR(MAX),
					PATIENT VARCHAR(MAX),
					ORGANIZATION VARCHAR(MAX),
					PAYER VARCHAR(MAX),
					ENCOUNTERCLASS VARCHAR(MAX),
					CODE VARCHAR(MAX),	
					DESCRIPTION VARCHAR(MAX),
					BASE_ENCOUNTER_COST VARCHAR(MAX),
					TOTAL_CLAIM_COST VARCHAR(MAX),
					PAYER_COVERAGE VARCHAR(MAX),
					REASONCODE VARCHAR(MAX),
					REASONDESCRIPTION
					 VARCHAR(MAX));

SELECT *FROM ENCOUNTERS

  ----/LOADING DATA USING BULK INSERT ...
BULK INSERT ENCOUNTERS
FROM 
	'C:\Users\VENU CHAVAN\OneDrive\Desktop\project 2 lern bay\encounters.csv'
WITH(fieldterminator=',',rowterminator='\n',firstrow=2);

----/0.3 TABLE ORGANIZATIONS
CREATE TABLE ORGANIZATION
						(Id VARCHAR(MAX),
						NAME VARCHAR(MAX),
						ADDRESS VARCHAR(MAX),
						CITY VARCHAR(MAX),
						STATE VARCHAR(MAX),
						 ZIP VARCHAR(MAX),
						 LAT VARCHAR(MAX),
						 LON VARCHAR(MAX))

SELECT *FROM ORGANIZATION
  ----/LOADING DATA USING BULK INSERT ...
BULK INSERT ORGANIZATION
FROM 
	'C:\Users\VENU CHAVAN\OneDrive\Desktop\project 2 lern bay\organizations.csv'
WITH(fieldterminator=',',rowterminator='\n',firstrow=2);



----/0.4 TABLE PATIENTS
CREATE TABLE PATIENTS
					(Id VARCHAR(MAX),	
					BIRTHDATE	VARCHAR(MAX),
					DEATHDATE VARCHAR(MAX),	
					PREFIX	VARCHAR(MAX),
					FIRST	VARCHAR(MAX),
					LAST	VARCHAR(MAX),
					SUFFIX	VARCHAR(MAX),
					MAIDEN	VARCHAR(MAX),
					MARITAL	VARCHAR(MAX),
					RACE	VARCHAR(MAX),
					ETHNICITY	VARCHAR(MAX),
					GENDER	VARCHAR(MAX),
					BIRTHPLACE	VARCHAR(MAX),
					ADDRESS	VARCHAR(MAX),
					CITY	VARCHAR(MAX),
					STATE	VARCHAR(MAX),
					COUNTY	VARCHAR(MAX),
					ZIP	VARCHAR(MAX),
					LAT	VARCHAR(MAX),
					LON VARCHAR(MAX));

 ----/LOADING DATA USING BULK INSERT ...
BULK INSERT PATIENTS
FROM 
	'C:\Users\VENU CHAVAN\OneDrive\Desktop\project 2 lern bay\patients.csv'
WITH(fieldterminator=',',rowterminator='\n',firstrow=2);


----/0.5 TABLE PROCEDURES 
CREATE TABLE PROCEDURES
						(START VARCHAR(MAX),
						STOP VARCHAR(MAX),	
						PATIENT	VARCHAR(MAX),
						ENCOUNTER	VARCHAR(MAX),
						CODE	VARCHAR(MAX),
						DESCRIPTION	VARCHAR(MAX),
						BASE_COST	VARCHAR(MAX),
						REASONCODE	VARCHAR(MAX),
						REASONDESCRIPTION VARCHAR(MAX));
 ----/LOADING DATA USING BULK INSERT ...
BULK INSERT PROCEDURES
FROM 
	'C:\Users\VENU CHAVAN\OneDrive\Desktop\project 2 lern bay\procedures.csv'
WITH(fieldterminator=',',rowterminator='\n',firstrow=2);

